"""FastAPI routers for all API routes."""

from . import (
    anomalies,
    budget,
    burn_rate,
    chargeback,
    cost_allocation,
    cost_explorer,
    cost_trend,
    data_quality,
    env_detail,
    filters,
    forecast,
    inventory,
    overview,
    pipeline,
    recommendations,
    search,
    settings,
    service_detail,
    showback,
    tag_policy,
    team_detail,
)

__all__ = [
    "anomalies",
    "budget",
    "burn_rate",
    "chargeback",
    "cost_allocation",
    "cost_explorer",
    "cost_trend",
    "data_quality",
    "env_detail",
    "filters",
    "forecast",
    "inventory",
    "overview",
    "pipeline",
    "recommendations",
    "search",
    "settings",
    "service_detail",
    "showback",
    "tag_policy",
    "team_detail",
]
